apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: jmx
      port: 9999
      targetPort: jmx