apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  labels:
    app: postgresql
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:14.1-alpine
        ports:
        - name: psql
          containerPort: 5432
        volumeMounts:
          - name: postgresql-data
            mountPath: /var/lib/postgresql/data
        envFrom:
        - configMapRef:
            name: postgresql-config
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-volume-claim