apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  type: NodePort
  ports:
  - name: psql
    port: 5432
    targetPort: psql
  selector:
    app: postgresql