kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-data
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: local-path
  capacity:
    storage: 128Mi
  accessModes: ["ReadWriteOnce"]
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/postgresql/data
  persistentVolumeReclaimPolicy: Delete