kind: PersistentVolume
apiVersion: v1
metadata:
  name: test-app-logs
  labels:
    type: local
    app: test-app
spec:
  storageClassName: local-path
  capacity:
    storage: 16Mi
  accessModes: ["ReadWriteMany"]
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/test-app/logs
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-app-logs
spec:
  storageClassName: local-path
  volumeName: test-app-logs
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 4Mi