apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-app
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
  - name: http
    port: 8080
    targetPort: http