apiVersion: v1
kind: ConfigMap
metadata:
  name: test-app-config
  labels:
    app: test-app
data:
  hello.default-name: K3s
  spring.datasource.host: ${POSTGRESQL_SERVICE_HOST}
  spring.datasource.port: ${POSTGRESQL_SERVICE_PORT}
  JDK_JAVA_OPTIONS: -XX:MaxRAMPercentage=50.0 -Djava.net.preferIPv4Stack=true
    -XX:+ExplicitGCInvokesConcurrent -Xlog:gc=info:file=logs/gc.log:time,tags:filecount=10,filesize=10m
    -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 3
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: k8s-test/test-app:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 192Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        ports:
        - name: http
          containerPort: 8080
        - name: jmx
          containerPort: 9999
        volumeMounts:
        - name: test-app-logs
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 10
          timeoutSeconds: 5
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5" ]
        envFrom:
        - configMapRef:
            name: test-app-config
      volumes:
      - name: test-app-logs
        emptyDir: {}