apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  template:
    spec:
      containers:
      - name: test-app
        image: ghcr.io/mcekovic/kubernetes-test/test-app:latest
        imagePullPolicy: Always